#eureka:
#  client:
#    service-url:
#      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
#      defaultZone: http://202.201.1.35:8761/eureka/

#  instance:
#    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
#    prefer-ip-address: true

spring:
  cloud:
    consul:
      host: 192.168.44.128