server:
  port: 8760
  forward-headers-strategy: FRAMEWORK

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#eureka:
#  client:
#    healthcheck:
#      # 使用health端点来代替心跳表明服务是否可用，反应到eureka server ui上服务的UP还是DOWN
#      enabled: true
#  instance:
#    # 获取此实例的相对健康检查URL路径，默认为/health
#    health-check-url-path: /actuator/health
spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: service-auth
          uri: lb://auth-server
          predicates:
            - Path=/oauth/** # 所有oauth开头的请求走这个路由
        - id: service-authbase
          # lb 表示负载均衡loadbalance
          uri: lb://base-server
          predicates:
            - Path=/v1/**,/swagger-ui.html/** # 按顺序匹配其他请求走这个路由
          filters:
            - TokenRelay=
        #          filters:
        #            - StripPrefix=1 # 转发之前将/api去掉
        - id: service-base
          uri: lb://base-server
          predicates:
            - Path=/** # 按顺序匹配其他请求走这个路由
      forwarded:
        enabled: false
