eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://eureka-server1:8761/eureka/, http://eureka-server2:8761/eureka/
    #  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    # prefer-ip-address: true
    # UI显示为系统hostname，实际访问时为此hostname
    # hostname: base-server
spring:
  redis:
    host: redis
  datasource:
    url: jdbc:mysql://172.18.0.1:3306/lzu
    username: lzu
    password: 1234lzu5678
