spring:
  cloud:
    consul:
      host: consul-client
  redis:
    host: redis
  #    host: 172.18.0.2
  datasource:
    url: jdbc:mysql://172.18.0.1:3306/lzu

#server:
#  #端口号
#  port: 9090
logstash:
  enabled: true
  host: elk
  port: 5045