management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    healthcheck:
      enabled: true #使用health端点来代替心跳表明服务是否可用，反应到eureka server ui上服务的UP还是DOWN
  instance:
    #   获取此实例的相对健康检查URL路径，默认为/health
    health-check-url-path: /actuator/health

spring:
  profiles:
    active: dev
  application:
    name: base-server
#logging:
#  file:   # 日志文件,绝对路径或相对路径
#  path:   # 保存日志文件目录路径
#  config: # 日志配置文件,Spring Boot默认使用classpath路径下的日志配置文件,如:logback.xml
#  level:  # 日志级别
#    org.springframework.web: DEBUG # 配置spring web日志级别