eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://${ip.addr}:8761/eureka/

#  instance:
#    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
#    prefer-ip-address: true

logging:
  level:
      com.forgqi.resourcebaseserver.client: debug
#swagger的配置
swagger:
  #正式线上，修改为true,就无法访问文档了

  production: false
  basic:
    enable: true
    username: admin
    password: 12345678