ip:
  #  addr: 192.168.44.128
  addr: localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  jackson:
    serialization:
      #  为了兼容之前,spring boot把默认改为了false
      #  the Jackson version is changed to 2.10. WRITE_DURATIONS_AS_TIMESTAMPS for serializing the Duration time stamps instead of the earlier WRITE_DATES_AS_TIMESTAMPS.
      #  By adding following property to the application.properties the service (and the serialization feature) will behave like pre 2.2
      write-durations-as-timestamps: true
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  #  cloud:
  #    consul:
  #      discovery:
  #        consul注册id要求字母开头，这个设置将hostname放在id第一部分，
  #        docker生成的hostname有可能是数字开头因此不行，
  #        自定义docker hostname将导致容器间不能通过hostname访问，通过设置docker的dns为consul的也许可行，
  #        目前先调整id中的hostname位置
  #        include-hostname-in-instance-id: true
  profiles:
    active: dev
  application:
    name: base-server
  #logging:
  #  file:   # 日志文件,绝对路径或相对路径
  #  path:   # 保存日志文件目录路径
  #  config: # 日志配置文件,Spring Boot默认使用classpath路径下的日志配置文件,如:logback.xml
  #  level:  # 日志级别
  #    org.springframework.web: DEBUG # 配置spring web日志级别
  #  data:
  #    redis:
  #      repositories:
  #        enabled: false
  redis:
    host: ${ip.addr}
    #    port: 6379
    database: 0 #0-15 16个库 默认0
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-wait: -1 #默认-1 最大连接阻塞等待时间
        max-idle: 8 #最大空闲连接 默认8
        min-idle: 0 #最小空闲连接
  jpa:
    # spring.jpa.open-in-view is enabled by default.
    # Therefore, database queries may be performed during view rendering.
    # Explicitly configure spring.jpa.open-in-view to disable this warning
    #    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      org.hibernate.envers.store_data_at_delete: true
  datasource:
    hikari:
      maximumPoolSize: 16
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ip.addr}:3306/lzu
    password: 12345678
    username: root
  servlet:
    multipart:
      max-file-size: 10MB # 上传文件最大为 10M （默认值 1M 根据自身业务自行控制即可）

server:
  #端口号
  port: 8080
  error:
    include-message: always
  #  security:
#    user:
#      name: 242bc36f
#      password: b5f6f597
#  只能支持特定的时间格式如Java8之前的date
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    timeZone: GMT+8
#feign:
##  okhttp:
##    enabled: true
#  client:
#    config:
#      default:
#        connectTimeout: 10000
#        readTimeout: 10000
