spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        # 解决hibernate multiple merge问题
        event:
          merge:
            entity_copy_observer: allow
logging:
  level:
    com.forgqi.resourcebaseserver.client: debug
