server:
    port: 8761
eureka:
    environment: prod
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS
# 单例没有实际作用
spring:
    profiles:
        active: peer1
    application:
        name: eureka-server-ha
