ip:
  addr: 192.168.44.128
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: auth-server
  redis:
    host: ${ip.addr}
    #    port: 6379
    database: 0 #0-15 16个库 默认0
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-wait: -1 #默认-1 最大连接阻塞等待时间
        max-idle: 8 #最大空闲连接 默认8
        min-idle: 0 #最小空闲连接
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ip.addr}:3306/lzu
    password: 12345678
    username: root
  cloud:
    consul:
      host: ${ip.addr}
      port: 8500
server:
  port: 8081
#debug: true
#eureka:
#  client:
#    service-url:
#      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
#      defaultZone: http://${ip.addr}:8761/eureka/